export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const REMOVE_PROJETO = 'REMOVE_PROJETO'

export const ADICIONA_NOFITIFACAO = 'ADICIONA_NOFITIFACAO'
export const REMOVE_NOTIFICACAO = 'REMOVE_NOTIFICACAO'